name: react-test-digitalocean
services:
- build_command: yarn build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: dpfernandes/react-test-digitalocean
  name: react-test-digitalocean
